{
 "title": "Database Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "MongoDB Operation Latency",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of operation latencies (e.g., reads, writes, queries) in MongoDB, grouped by operation type, over the past 5 minutes. It helps monitor the performance of various MongoDB operations, identifying potential slowdowns in specific operation types.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(mongodb_mongod_op_latencies_latency_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Data Size by Database",
   "type": "timeseries",
   "description": "This query calculates the total data size (in bytes) for each MongoDB database, excluding the admin, config, and local databases. It helps track the storage usage in user databases, providing insights into their growth and resource consumption.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(database) (mongodb_mongod_db_data_size_bytes{database!~\"config|local|admin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Query Rate",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of MongoDB query operations over the past 5 minutes. It helps monitor the frequency of query executions, indicating the level of query activity on the MongoDB instance.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"query\"}[5m])\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Read Latency by Database",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of read latency for each MongoDB database over the past 5 minutes. It helps assess the performance of database read operations, identifying any potential latency issues at the database level.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(database) (rate(mongodb_collstats_latencyStats_reads_latency[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Index Size by Database",
   "type": "timeseries",
   "description": "This query calculates the total index size (in bytes) for each MongoDB database, excluding the admin, config, and local databases. It helps track the storage usage dedicated to indexes in user databases, providing insights into indexing efficiency and resource usage.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(database) (mongodb_mongod_db_index_size_bytes{database!~\"admin|local|config\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Insert Rate",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of MongoDB insert operations over the past 5 minutes. It helps monitor the frequency of data insertions, indicating the level of write activity on the MongoDB instance.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"insert\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Write Latency by Database",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of write latency for each MongoDB database over the past 5 minutes. It helps monitor the performance of database write operations, highlighting potential delays or performance issues in write-heavy databases.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(database) (rate(mongodb_collstats_latencyStats_writes_latency[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Document Count by Database",
   "type": "timeseries",
   "description": "This query calculates the total number of objects in each MongoDB database, excluding the admin, config, and local databases. It helps track the object count in user databases, providing insight into database size and activity.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by(database) (mongodb_dbstats_objects{database!~\"admin|config|local\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Delete Rate",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of MongoDB delete operations over the past 5 minutes. It helps monitor the frequency of data deletions, providing insight into the delete activity on the MongoDB instance.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"delete\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Collection Count by Database",
   "type": "timeseries",
   "description": "This query calculates the total number of collections in each MongoDB database, excluding the admin, config, and local databases. It helps monitor the structure and organization of user databases by tracking how many collections they contain.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(database) (mongodb_dbstats_collections{database!~\"admin|local|config\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Update Rate",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of MongoDB update operations over the past 5 minutes. It helps monitor the frequency of data updates, indicating the level of modification activity on the MongoDB instance.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"update\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of new MongoDB connections over the past 5 minutes. It helps monitor the connection load to the MongoDB instance, providing insight into the frequency of incoming connections.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(mongodb_connections{state=\"active\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}