services:
  ivt-py-frontend:
      image: ghcr.io/meyersa/app-test-py:500eeb35930f8a7cfcc43ef1ac257fa791f5a097
      container_name: ivt-py-frontend
      restart: unless-stopped
      mem_limit: 256m
      cpus: 0.5
      networks:
        - operations_traefik
      labels: 
        - "alloy.blackbox=ivt-py.${BACKEND_DOMAIN}"
        - "traefik.enable=true"
        - "traefik.http.routers.ivt-py-frontend.rule=Host(`ivt-py.${BACKEND_DOMAIN}`)"
        - "traefik.http.routers.ivt-py-frontend.entrypoints=websecure"
        - "traefik.http.services.ivt-py-frontend.loadbalancer.server.port=8000"
        - "traefik.http.routers.ivt-py-frontend.middlewares=noindex-header@file"

networks:
  operations_traefik:
    external: true