services:
  # Slated for replacement soon
  whoami-frontend:
      image: traefik/whoami
      container_name: whoami-frontend
      restart: unless-stopped
      mem_limit: 256m
      cpus: 0.5
      networks:
        - operations_traefik
      labels: 
        - "alloy.blackbox=whoami.${BACKEND_DOMAIN}"
        - "traefik.enable=true"
        - "traefik.http.routers.whoami-frontend.rule=Host(`whoami.${BACKEND_DOMAIN}`)"
        - "traefik.http.routers.whoami-frontend.entrypoints=websecure"
        - "traefik.http.services.whoami-frontend.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami-frontend.middlewares=noindex-header@file"

networks:
  operations_traefik:
    external: true