services:
  mongodb:
    image: mongo:8.3.4
    container_name: mongodb
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - ./compose.mongo.env
    volumes:
      - ${DATA_DIR}/mongo:/data/db
    networks:
      - mongodb

networks:
  mongodb: