{
 "title": "Log Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Log Lines Read Rate by Container",
   "type": "timeseries",
   "description": "This query calculates the per-minute rate of custom log lines read from each container over the past 5 minutes. It helps monitor log processing activity for each container, indicating the volume of logs being consumed.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(loki_process_custom_log_lines_read{container_name!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Error Percent by Container (Last 5 Minutes)",
   "type": "timeseries",
   "description": "Percentage of critical/severe docker logs out of total logs over the past hour.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 *\n(\n  sum by(container_name) (\n    rate({job=\"docker\"} |~ \"critical|err|severe|panic\" [1h])\n  )\n  /\n  sum by(container_name) (\n    rate({job=\"docker\"} [1h])\n  )\n)\n",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "JournalCTL Percent Error",
   "type": "timeseries",
   "description": "This query calculates the total count of log entries containing the word \"critical\" for each instance within the \"journalctl\" job over the past 5 minutes. It helps monitor the frequency of critical system events or errors logged by each instance in a short time period.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * sum by(instance) (count_over_time({job=\"journalctl\"} |~ \"critical|err|severe|panic\" [5m]))\r\n/\r\nsum by(instance) (count_over_time({job=\"journalctl\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Error Logs by Container (Last 5 Minutes)",
   "type": "timeseries",
   "description": "This query calculates the total count of log entries containing high-severity keywords (\"critical\", \"err\", \"severe\", \"panic\") for each instance within the \"docker\" job over the past 5 minutes. It helps track the frequency of critical or error-related events per instance.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(container_name) (count_over_time({job=\"docker\"} |~ `critical|err|severe|panic` [5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JournalCTL Logs (Last 5 Minutes)",
   "type": "timeseries",
   "description": "This query calculates the total number of log entries for each instance within the \"journalctl\" job over the past 5 minutes. It helps track the overall log volume generated by each system or service, providing insight into log activity within a short time window.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"journalctl\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Lines Received Rate",
   "type": "timeseries",
   "description": "This query calculates the per-second rate of log lines received by Loki's distributor over the past 5 minutes. It helps monitor the rate at which logs are being ingested into Loki in real-time.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[5m])",
     "legendFormat": "Log Lines Received"
    }
   ]
  },
  {
   "title": "Docker Logs by Container (Last 5 Minutes)",
   "type": "timeseries",
   "description": "This query identifies the top 5 Docker containers with the highest number of events (e.g., starts or stops) over the last 5 minutes. It helps highlight the most active containers, providing valuable insights into container activity and resource usage for efficient monitoring and troubleshooting.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(container_name) (count_over_time({job=\"docker\"} [5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JournalCTL Error Logs (Last 5 Minutes)",
   "type": "timeseries",
   "description": "This query calculates the total count of log entries containing high-severity keywords (\"critical\", \"err\", \"severe\", \"panic\") for each instance within the \"journalctl\" job over the past 5 minutes. It helps track the frequency of critical or error-related system events or failures logged by each instance.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"journalctl\"} |~ \"critical|err|severe|panic\" [5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Log Lines Received (Last Hour)",
   "type": "stat",
   "description": "This query calculates the total number of log lines received by Loki's distributor over the past 1 hour. It helps track the overall log ingestion volume during that time period.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "logs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(loki_distributor_lines_received_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Docker Logs (Last Hour)",
   "type": "stat",
   "description": "This query calculates the total number of log entries for each instance within the \"docker\" job over the past 1 hour. It helps track the overall log volume generated by each instance, providing insight into log activity over a longer time period.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "logs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"docker\"} [1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total JournalCTL Logs (Last Hour)",
   "type": "stat",
   "description": "This query calculates the total number of log entries for each instance within the \"journalctl\" job over the past 1 hour. It helps track the overall log volume generated by each instance, providing insight into log activity over a longer time period.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "logs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({job=\"journalctl\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}