{
 "title": "System Stats",
 "description": "Overview of systems being monitored",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "This query calculates the percentage of CPU time spent on non-idle modes (e.g., user, system) for each instance over the past 5 minutes. It provides insight into the CPU utilization, helping to understand how much of the CPU's capacity is being actively used compared to being idle.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / sum by(instance) (rate(node_cpu_seconds_total[5m])) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "description": "This query counts the number of instances that are currently up (i.e., not in a down state) within the \"integrations/unix\" job. It helps track the availability of monitored instances, providing a snapshot of which instances are currently operational.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "up" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (up{job=\"integrations/unix\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Total)",
   "type": "stat",
   "description": "This query calculates the total amount of memory (in bytes) across all nodes being monitored. It provides a system-wide view of the total memory available on all nodes, useful for overall resource monitoring.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage (Total)",
   "type": "stat",
   "description": "This query calculates the total disk space (in bytes) across all nodes, excluding filesystems with the types tmpfs and overlay. It helps monitor the actual disk space available on persistent storage, excluding temporary and overlay filesystems.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (engine_daemon_container_states_containers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "description": "This query calculates the per-second rate of interrupts for each instance over the past 5 minutes. It helps monitor the frequency of hardware interrupts, providing insight into the system's interrupt load and potential performance bottlenecks.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_intr_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO Pressure",
   "type": "timeseries",
   "description": "This query calculates the average rate of time spent waiting for I/O operations to complete on each instance over the past 5 minutes. It provides insight into potential I/O bottlenecks or delays on the system.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_pressure_io_waiting_seconds_total{job=\"integrations/unix\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "This query calculates the percentage of memory used by each instance, based on the total available memory and the available memory. It provides insight into the memory consumption, helping to understand how much memory is being utilized compared to the total available memory on the system.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (1 - (node_memory_MemAvailable_bytes{job=\"integrations/unix\"} / node_memory_MemTotal_bytes{job=\"integrations/unix\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "This query calculates the total per-second rate of network traffic (both incoming and outgoing) for each instance over the past 5 minutes. It provides insight into the overall network usage, combining both receive and transmit data rates for each instance.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) ((irate(node_network_receive_bytes_total[5m])) + (irate(node_network_transmit_bytes_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "description": "This query calculates the average rate of time spent waiting due to memory pressure on each instance over the past 5 minutes. It helps identify instances experiencing memory-related delays, indicating potential resource contention or memory shortages.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_pressure_memory_waiting_seconds_total{job=\"integrations/unix\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "This query calculates the percentage of used disk space for each instance, specifically for the root filesystem (\"/\"). It compares the free space to the total disk space, providing insight into how much of the filesystem is utilized compared to the total available storage.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (100 - (node_filesystem_free_bytes{mountpoint=\"/\", job=\"integrations/unix\"} / node_filesystem_size_bytes{mountpoint=\"/\", job=\"integrations/unix\"} * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "This query calculates the per-second rate of disk read and write operations for the sda device on each instance over the past 10 minutes. It provides insight into the total disk activity, combining both read and write operations for the specified disk device.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_disk_written_bytes_total{device=\"sda\"}[5m])) + sum by(instance) (irate(node_disk_read_bytes_total{device=\"sda\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "timeseries",
   "description": "This query calculates the average percentage of time spent waiting due to CPU pressure on each instance over the past 5 minutes. It helps monitor instances that may be experiencing CPU resource contention, providing insight into system performance and load.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_pressure_cpu_waiting_seconds_total{job=\"integrations/unix\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}